context.properties = {
    core.daemon = true
    log.level = 2
}

context.modules = [
    { name = libpipewire-module-rt
      args = { nice.level = -11 }
      flags = [ ifexists nofail ] }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-metadata }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-link-factory }
    { name = libpipewire-module-pulse-tunnel
      args = {
          tunnel.mode = "sink"
          stream.props = {
              node.name = "bubblewand-sandbox-output"
              media.class = "Audio/Sink"
          }
      } }
    { name = libpipewire-module-pulse-tunnel
      args = {
          tunnel.mode = "source"
          stream.props = {
              node.name = "bubblewand-sandbox-input"
              media.class = "Audio/Source"
          }
      } }
]
